name: Crypto Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri yükle
        run: pip install -r requirements.txt

      - name: Dosyaları kontrol et
        run: ls -R

      - name: Bot çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python pump_bot.py
